M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-11-20T00:47:47+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-20T00:47:47+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
%
G90
G05
T1
X-0.8874Y0.315
X1.4748Y-0.3543
M30
